Message.user is deprecated, replacing with .author
This avoid these warnings:
```
Error: You are accessing ChatMessagePF2e#user which has been migrated to ChatMessagePF2e#author
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
```